services:
  app:
    # Build directly from the GitHub repository
    build: https://github.com/Fieze/gasstrom.git#main
    image: gas-strom-app
    ports:
      - "4735:4735"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/database.sqlite
